### ISSUE TITLE
data_list is empty

### ISSUE THREAD

**Issue by WishZ** [TikHubIO/Douyin-TikTok-API-Python-SDK#17]
douyin_api = DouyinAPI(token)

r = asyncio.run(douyin_api.get_douyin_search_data_products('猫', 0, 10))

print(r)

{'status': True, 'platform': 'douyin', 'endpoint': '/douyin/search_data_products/', 'total_time': 0.9287, 'message': None, 'keyword': '猫', 'challenge_id': None, 'has_more': False, 'cursor': 0, 'next_url': None, 'count': 0, 'data_list': []}

**Comment by Evil0ctal** [comment]
抖音把我们的爬虫拉黑了，晚点会修复。

**Comment by bxiaoj** [comment]
> douyin_api = DouyinAPI(token)
> 
> r = asyncio.run(douyin_api.get_douyin_search_data_products('猫', 0, 10))
> 
> print(r)
> 
> {'status': True, 'platform': 'douyin', 'endpoint': '/douyin/search_data_products/', 'total_time': 0.9287, 'message': None, 'keyword': '猫', 'challenge_id': None, 'has_more': False, 'cursor': 0, 'next_url': None, 'count': 0, 'data_list': []}

[http://vproctol.zeed.ink/](http://vproctol.zeed.ink/)可以用，能解决你的问题，免费稳定（突破黑名单和IP限制）

**Comment by bxiaoj** [comment]
[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.
